{
 "title": "Kafka Producer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Rate(ACKS/ms)",
   "type": "graph",
   "description": "Average number of responses received per second.\nThe response rate represents the rate of responses received from brokers (ACKS) based on ACK setting",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_response_rate", "legendFormat": "{{clientId}} / {{producer}}" }
   ]
  },
  {
   "title": "Request Rate(Request to brokers/sec)",
   "type": "graph",
   "description": "Average number of requests received per second.\nThe request rate is the rate at which producers send data to brokers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_request_rate", "legendFormat": "{{clientId}} / {{producer}}" }
   ]
  },
  {
   "title": "Compression Average Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "IO wait time (ns)",
   "type": "graph",
   "description": "io-wait-time-ns-avg Average length of time the I/O thread spent waiting for a socket (in ns)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "Producer network (outgoing bytes sent per second)",
   "type": "graph",
   "description": "producer network throughput.\nThe average number of outgoing bytes sent per second to all servers.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "Producer Connections(Active)",
   "type": "graph",
   "description": "The current number of active connections.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_connection_count",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "Buffer Wait",
   "type": "graph",
   "description": "Wait time in buffer before pushing to broker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_time_total",
     "legendFormat": "{{clientId}}~{{job}}"
    }
   ]
  },
  {
   "title": "Average Bytes sent (per partition / per request)",
   "type": "graph",
   "description": "The average number of bytes sent per partition per request",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_batch_size_avg", "legendFormat": "{{clientId}}~{{job}}" }
   ]
  },
  {
   "title": "Request Latency Avg(ms)",
   "type": "graph",
   "description": "The average request latency in ms. The average request latency is a measure of the amount of time between when KafkaProducer.send() was called until the producer receives a response from the broker. (Acks)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "Request Latency Avg(ms)",
   "type": "graph",
   "description": "The average request latency in ms. The average request latency is a measure of the amount of time between when KafkaProducer.send() was called until the producer receives a response from the broker. (Acks)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "Response Total",
   "type": "graph",
   "description": "Total response bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_response_total)",
     "legendFormat": "{{clientId}} / {{producer}}"
    }
   ]
  },
  {
   "title": "IO Ratio (fraction time IO)",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent doing I/O.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_io_ratio", "legendFormat": "{{clientId}} / {{producer}}" }
   ]
  },
  {
   "title": "IO Wait Ratio (fraction time IO)",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent waiting.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_io_wait_ratio", "legendFormat": "{{clientId}} / {{producer}}" }
   ]
  }
 ]
}